[project]
name = "chatterbox-tts"
version = "0.1.6"
description = "Chatterbox: Open Source TTS and Voice Conversion by Resemble AI"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "resemble-ai", email = "engineering@resemble.ai"}
]
dependencies = [
    "numpy>=1.26.0", # Modified for Google Colab compatibility
    "librosa>=0.10.0", # Modified for Google Colab compatibility 
    "torch>=2.0.0", # Modified for Google Colab compatibility (Relaxed from ==2.6.0 to avoid conflicts with pre-installed)
    "torchaudio>=2.0.0", 
    "transformers>=4.46.0", 
    "diffusers>=0.29.0", 
    "resemble-perth>=1.0.1", 
    "conformer>=0.3.2",
    "safetensors>=0.5.0", 
    "s3tokenizer",
    "spacy-pkuseg",
    "pykakasi>=2.3.0",
    "pyloudnorm",
    "omegaconf",
    "gradio>=4.0.0",
    "torchcodec>=0.9.1",  # Added for torchaudio WAV saving
]

[project.urls]
Homepage = "https://github.com/resemble-ai/chatterbox"
Repository = "https://github.com/resemble-ai/chatterbox"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
