[project]
name = "chatterbox"
version = "0.1"
readme = "README.md"
dependencies = [
    "numpy==1.26.0",
    "resampy==0.4.3",
    "librosa==0.10.0",
    "s3tokenizer",
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "transformers==4.46.3",
    "diffusers==0.29.0",
    "resemble-perth==1.0.1",
    "silero-vad==5.1.2",

    "omegaconf==2.3.0",
    "conformer==0.3.2",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
