[project]
name = "chatterbox"
version = "0.1.4"
description = "Chatterbox: Open Source TTS and Voice Conversion by Resemble AI"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "resemble-ai", email = "engineering@resemble.ai"}
]
dependencies = [
    "numpy>=2.3.3",
    "librosa==0.11.0",
    "s3tokenizer",
    "torch==2.9.1",
    "torchaudio==2.9.1",
    "torchcodec==0.8.1",
    "transformers>=4.53.0",
    "diffusers==0.35.2",
    "resemble-perth==1.0.1",
    "conformer==0.3.2",
    "safetensors>=0.7.0",
    "spacy-pkuseg==1.0.1",
    "pykakasi==2.3.0",
    "russian-text-stresser@git+https://github.com/michaelcreatesstuff/add-stress-to-epub.git@60c5c3d31cd5472e394d64cf74d6f1d7b31425e2",

]

[project.urls]
Homepage = "https://github.com/michaelcreatesstuff/chatterbox"
Repository = "https://github.com/michaelcreatesstuff/chatterbox"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
