[project]
name = "chatterbox-tts"
version = "0.3.3"
description = "Chatterbox: Open Source TTS and Voice Conversion by Resemble AI"
readme = "README.md"
requires-python = "==3.12.*"
license = {file = "LICENSE"}
authors = [
    {name = "resemble-ai", email = "engineering@resemble.ai"}
]
dependencies = [
    "torch<2.9",
    "torchaudio",
    "scipy",
    "numpy",
    "soundfile",
    "s3tokenizer",
    "transformers",
    "huggingface_hub",
    "diffusers",
    "omegaconf",
    "conformer",
    "safetensors",
    "peft",
    "psutil",
    "loguru",
    "gradio",
    "setuptools<81.0",
    "dicta_onnx",
    "spacy_pkuseg",
    "pykakasi"
]

[project.urls]
Homepage = "https://github.com/resemble-ai/chatterbox"
Repository = "https://github.com/resemble-ai/chatterbox"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pip]
extra-index-url = ["https://download.pytorch.org/whl/cu129"]
